### PR TITLE
Fix big gun rocket exploding when spawned.

### LINKED ISSUE #1006: rocket from big gun explodes immediately

### PR DESCRIPTION
**Pull request by TokyoSU**
- Fix a possible crash with biggun if CreateItem() is saturated.

Fix #1006

### CODE REVIEW

File: TombEngine/Objects/TR3/Vehicles/big_gun.cpp [hunk 1]
```diff
@@ -111,36 +111,30 @@ namespace TEN::Entities::Vehicles
...
 			projectileItem->ItemFlags[0] = BGUN_FLAG_UP_DOWN;
+			projectileItem->HitPoints = 1000; // NOTE: Time before it explose, TR5 use it, if 0, it will explode by default.
 
 			AddActiveItem(itemNumber);
-
-			lara->LeftArm.GunSmoke = 32;
-
 			for (int i = 0; i < 5; i++)
-				TriggerGunSmoke(pos.x, pos.y, pos.z, 0, 0, 0, 1, LaraWeaponType::RocketLauncher, lara->LeftArm.GunSmoke);
+				TriggerGunSmoke(pos.x, pos.y, pos.z, 0, 0, 0, 1, LaraWeaponType::RocketLauncher, 32);
```
Comment (Kubsy) [inline TombEngine/Objects/TR3/Vehicles/big_gun.cpp:137]: what's 32?

Comment (TokyoSU) [reply TombEngine/Objects/TR3/Vehicles/big_gun.cpp:137]: value assigned to lara->LeftArm.GunSmoke, which is clearly not needed to do the smoke timer :)

File: TombEngine/Objects/TR3/Vehicles/big_gun.cpp [hunk 2]
```diff
@@ -111,36 +111,30 @@ namespace TEN::Entities::Vehicles
...
 			projectileItem->Pose.Orientation = EulerAngles(
 				-((bigGun->XOrientFrame - 32) * ANGLE(1.0f)),
 				bigGunItem->Pose.Orientation.y,
 				0
 			);
+			InitialiseItem(itemNumber);
+
+			projectileItem->Animation.Velocity.z = 16;
 			projectileItem->ItemFlags[0] = BGUN_FLAG_UP_DOWN;
+			projectileItem->HitPoints = 1000; // NOTE: Time before it explose, TR5 use it, if 0, it will explode by default.
```
Comment (Lwmte) [inline TombEngine/Objects/TR3/Vehicles/big_gun.cpp:133]: "Explode", not "explose" :)

File: TombEngine/Objects/TR3/Vehicles/big_gun.cpp [hunk 3]
```diff
@@ -111,36 +111,30 @@ namespace TEN::Entities::Vehicles
 
 	void BigGunFire(ItemInfo* bigGunItem, ItemInfo* laraItem)
 	{
-		auto* lara = GetLaraInfo(laraItem);
 		auto* bigGun = GetBigGunInfo(bigGunItem);
 
 		short itemNumber = CreateItem();
-		auto* projectileItem = &g_Level.Items[itemNumber];
-
 		if (itemNumber != NO_ITEM)
```
Comment (Lwmte) [inline TombEngine/Objects/TR3/Vehicles/big_gun.cpp:117]: You can invert the condition and do an early exit from the function, this will simplify code a bit. Since your changes are minor, I don't think it will affect PR readability that much.

File: TombEngine/Objects/TR3/Vehicles/big_gun.cpp (hunk 1 above)
Comment (Lwmte) [reply TombEngine/Objects/TR3/Vehicles/big_gun.cpp:137]: I don't understand, can you elaborate? How it worked before if it referenced that `lara->LeftArm.GunSmoke` value directly?

Comment (TokyoSU) [reply TombEngine/Objects/TR3/Vehicles/big_gun.cpp:137]: It just use 32 as value and assign it to lara gunsmoke and pass it as argument to triggergunsmoke, which is not recommanded

Comment (Lwmte) [reply TombEngine/Objects/TR3/Vehicles/big_gun.cpp:137]: After discussion on a discord, I suggest to rollback this line to use `LeftArm.GunSmoke` again.

File: TombEngine/Objects/TR3/Vehicles/big_gun.cpp (hunk 2 above)
Comment (TokyoSU) [reply TombEngine/Objects/TR3/Vehicles/big_gun.cpp:133]: Fixed :)

File: TombEngine/Objects/TR3/Vehicles/big_gun.cpp (hunk 3 above)
Comment (TokyoSU) [reply TombEngine/Objects/TR3/Vehicles/big_gun.cpp:117]: Done

**Review by Sezzary — APPROVED** [review]
I don't know what you guys are planning with the `32`, but looks good otherwise.

File: TombEngine/Objects/TR3/Vehicles/big_gun.cpp (hunk 1 above)
Comment (TokyoSU) [reply TombEngine/Objects/TR3/Vehicles/big_gun.cpp]: Done

**Comment by TokyoSU** [comment]
Waiting for approve :)
